### ISSUE TITLE
Theoretical Calibration not working for new IOR

### ISSUE THREAD

**Issue by wblumberg** [hagne/atm-py#18]
The first code block in the example notebook example_POPS_calibration has some issues when the ior parameter is changed.  Please see the image for an example of the error!

If the ior is changed to 1.5+0.001j it runs fine.  No idea about the accuracy though!

![Screen Shot 2019-11-14 at 5 02 20 PM](https://user-images.githubusercontent.com/7607087/68899854-989c5c80-0700-11ea-926b-5a6067701009.png)

**Comment by hagne** [comment]
This happened because at that no_cal_pts the resulting calibration function was monotonic. I rewrote the function in a way that no_cal_pts is steadily decreased until the function is monotonic.
